awsapp/urls.py
from django.conf.urls import url, include
from . import views as views

urlpatterns = [
    url(r'^s3/file/upload/$', views.S3FileUploadView.as_view(), name='s3-file-upload'),
    url(r'^s3/new/bucket/$', views.create_bucket, name="s3-new-bucket"),

]

awsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^awsweb/',include('awsapp.urls', namespace='awsapp')),
]

awsapp/models.py
from django.db import models

# Create your models here.

awsapp/forms.py
from django import forms
from .utils import list_all_buckets


class S3FileUploadForm(forms.Form):
    """
    Class the presents a form for uploading a file

    """

    bucket_list = forms.ChoiceField(
        choices=list_all_buckets(), label="Select a Bucket", required=True)
    s3_file = forms.FileField(label="Upload a File to S3 Bucket", required=True)


class S3NewBucketForm(forms.Form):
    bucket_name = forms.CharField(label="Bucket Name", required=True)

awsapp/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission, User
from django.core.files.storage import default_storage
from django.contrib.auth.hashers import check_password
from .forms import S3FileUploadForm, S3NewBucketForm
import os
from .utils import upload_to_s3, create_s3_bucket

AWS_BASE_URL = "https://s3.amazonaws.com/"


# Create your views here.

class S3FileUploadView(TemplateView):
    template_name = "awsapp/s3_bucket_file_upload.html"

    def get_context_data(self, **kwargs):
        context = super(S3FileUploadView,
                        self).get_context_data(**kwargs)
        s3_form = S3FileUploadForm()
        s3_new_bucket = S3NewBucketForm()
        context.update({"s3_form": s3_form, "new_bucket": s3_new_bucket, "status": False})

        return context

    def post(self, request, *args, **kwargs):
        s3_form = S3FileUploadForm(request.POST, request.FILES)
        if s3_form.is_valid():
            # The uploaded file
            s3_file = request.FILES.get('s3_file')
            bucket_name = request.POST.get('bucket_list')
            status = upload_to_s3(s3_file, bucket_name)
            context = {"file_url": AWS_BASE_URL + bucket_name + "/" + s3_file.name}
            context.update({"status": status})
            return render(request, "awsapp/s3_bucket_file_upload.html", context)

        else:
            s3_form = S3FileUploadForm()
            context = {"s3_form": s3_form, "status": False}
            return render(request, "awsapp/s3_bucket_file_upload.html", context)


def create_bucket(request):
    """
    Function based view used to create new bucket
    :param request:
    :return:
    """
    s3_new_bucket = S3NewBucketForm(request.POST)

    if s3_new_bucket.is_valid():
        bucket_name = request.POST.get('bucket_name')

        bucket_status = create_s3_bucket(bucket_name)

        context = {"bucket_status": bucket_status, "status": False}

        s3_form = S3FileUploadForm()
        s3_new_bucket = S3NewBucketForm()
        context.update({"s3_form": s3_form, "new_bucket": s3_new_bucket})

        return render(request, "awsapp/s3_bucket_file_upload.html", context)

    else:
        s3_form = S3FileUploadForm()
        s3_new_bucket = S3NewBucketForm()
        context = {}
        context.update({"s3_form": s3_form, "new_bucket": s3_new_bucket, "bucket_status": False})

        return render(request, "awsapp/s3_bucket_file_upload.html", context)

awsapp/templates/awsapp/base.html
{% load static from staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>AWS WEB</title>
  {% include 'awsapp/static.html' %}

</head>

<body>
{% include 'awsapp/navbar.html' %}

  {% block content %}
    <div class="container-fluid">

    </div>
  {% endblock %}

</body>




</html>

awsapp/templates/awsapp/navbar.html
{% load static from staticfiles %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">
        AWS-WEB
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li><a href="{% url 'awsapp:s3-file-upload' %}">S3 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link2</a></li>
        <li><a href="#">Link3</a></li>
        <li><a href="#">Link4</a></li>
        <li><a href="#">Link5</a></li>








        </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

awsapp/templates/awsapp/s3_bucket_file_upload.html
{% extends "awsapp/base.html" %}

{% block content %}
<div class="container">
    {% if bucket_status == True %}
        <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Success</strong> Bucket has been created.
</div>
    {% elif bucket_status == False %}
    <div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Warning!!</strong> Bucket with name already exists.</div>
    {% endif %}
    <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
  Create New Bucket
</button>
    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create New S3 Bucket</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'awsapp:s3-new-bucket' %}">
            {% csrf_token %}
            {{ new_bucket.as_p }}


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create Bucket</button>

      </div>
        </form>
    </div>
  </div>
</div>
</div>
<h3>Upload File to S3 Bucket</h3>
   {% if status == False %}
    <form method="post" action="{% url 'awsapp:s3-file-upload' %}" enctype = "multipart/form-data" class="form-horizontal">
                            {% csrf_token %}
                            {{ s3_form.as_p }}

                                <button type="submit">Upload File</button>
                        </form>
    {% else %}
        <a href="{{ file_url}}">Click here to access the File URL</a>
    {% endif %}
</div>


{% endblock content %}

awsapp/templates/awsapp/static.html
{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


<!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>